### ISSUE TITLE
Fails to upload

### ISSUE THREAD

**Issue by vext01** [4refr0nt/luatool#18]
Hi,

First time using a nodemcu, so excuse me if I did this wrong. Host is OpenBSD, board is the new nodemcu amica.

```
$ sudo python2.7 luatool/luatool.py -p /dev/cuaU0

->file.open("main.lua", "w") -> ok
->file.close() -> ok
->file.remove("main.lua") -> ok
->file.open("main.lua", "w+")

ERROR
 send string    : 'file.open("main.lua", "w+")'
 expected echo  : 'file.open("main.lua", "w+")'
 but got answer : ' file.open("main.lua", "w+")'

Traceback (most recent call last):
  File "luatool/luatool.py", line 143, in <module>
    writeln("file.open(\""+args.dest+"\", \"w+\")\r")
  File "luatool/luatool.py", line 58, in writeln
    raise Exception('Error sending data to MCU\r\n\r\n')
Exception: Error sending data to MCU
```

Looks like just an extra space was received.

**Comment by vext01** [comment]
I tried some more and occasionally was getting:
```
ERROR
 send string    : 'file.open("main.lua", "w")'
 expected echo  : 'file.open("main.lua", "w")'
 but got answer : 'ile.open("main.lua", "w")'
```

i.e. 'f' missing from 'file.open'. I reset the board and can't seem to see that effect anymore.

Anyhow, stripping the line seems to work ok:

```
diff --git a/luatool/luatool.py b/luatool/luatool.py
index d2d237e..db85086 100755
--- a/luatool/luatool.py
+++ b/luatool/luatool.py
@@ -42,6 +42,7 @@ def writeln(data, check = 1):
                raise Exception('No proper answer from MCU')
            if char == chr(13) or char == chr(10) : # LF or CR
               if line != '':
+                 line = line.strip()
                  if line+'\r' == data :
                     sys.stdout.write(" -> ok")
                  else :

```

**Comment by 4refr0nt** [comment]
Hi!
thanks!

**Comment by vext01** [comment]
Actually, I am getting this a lot. If I repeatedly retry, it eventually works:

```
 send string    : 'file.open("user.lua", "w")'
 expected echo  : 'file.open("user.lua", "w")'
 but got answer : 'ile.open("user.lua", "w")'
```

Please re-open issue.

**Comment by 4refr0nt** [comment]
Hi!

please try at line 35: sleep(0.3) change to sleep(0.4)

**Comment by vext01** [comment]
same, but I think it is just interference with other stuff coming out the serial port. I just saw parts of the welcome banner in the error message.

My board prints this as is boots:

```
NodeMCU 0.9.5 build 20150403  powered by Lua 5.1.4
Will run user.lc/user.lua in 1000ms
>
> cannot open user.lua
```

**Comment by vext01** [comment]
I think you can close this without changing the code, and possibly reverting the strip(). You just can't upload if the mcu is printing to the serial line at the same time.
