### ISSUE TITLE
When sending data containing '>', unable to verify response

### ISSUE THREAD

**Issue by trisk** [4refr0nt/luatool#27]
The check in `writeln` looks for '>' to detect a prompt (end of response). Unfortunately, it just takes the first '>' that appears instead of checking only the beginning of a new line. It doesn't seem to affect the written data, though.

Example output with this problem:
```
->file.writeline([==[handler["/"] = function(c, params)]==]) -> ok
->file.writeline([==[local buf = "<h1>ESP8266 Web Server</h1>"]==])
->file.writeline([==[buf = buf .. "<p>GPIO0 <a href=\"?gpio0=1\"><button>ON</button></a>&nbsp;<a href=\"?gpio0=0\"><button>OFF</button></a>"]==])
->file.writeline([==[buf = buf .. "<form action=\"\" method=\"GET\">"]==])
->file.writeline([==[buf = buf .. "<label>ON for (milliseconds)</label><input name=\"gpio0_time\" type=\"number\" min=\"100\" max=\"10000\" default=\"1000\"/>"]==])
->file.writeline([==[buf = buf .. "<input type=\"submit\"/></form></p>"]==])
->file.writeline([==[if params.gpio0 == "1" then]==]) -> ok
->file.writeline([==[gpio.write(gpio0, gpio.HIGH)]==]) -> ok
->file.writeline([==[elseif params.gpio0 == "0" then]==]) -> ok
```

Notice the missing ` -> ok` for the lines containing the '>' character.

**Comment by andrewgho** [comment]
The following is a smaller repro case for this bug. Create a file `test.lua` with a single line:

````lua
gt = ">"
````

Run `luatool.py -f test.lua` (with whatever other port/baud arguments you would normally use):

````
->file.open("test.lua", "w") -> ok
->file.close() -> ok
->file.remove("test.lua") -> ok
->file.open("test.lua", "w+") -> ok
->file.writeline([==[gt = ">"]==])
->file.flush()

ERROR
 send string    : 'file.flush()'
 expected echo  : 'file.flush()'
 but got answer : '"]==])'

Traceback (most recent call last):
  File "/Users/andrew/work/luatool/luatool/luatool.py", line 294, in <module>
    transport.writeln("file.flush()\r")
  File "/Users/andrew/work/luatool/luatool/luatool.py", line 107, in writeln
    self.performcheck(data)
  File "/Users/andrew/work/luatool/luatool/luatool.py", line 77, in performcheck
    raise Exception('Error sending data to MCU\r\n\r\n')
Exception: Error sending data to MCU
````

The pull request I just made fixes this problem.
