### ISSUE TITLE
Failure to compile code

### ISSUE THREAD

**Issue by neiljp** [4refr0nt/luatool#38]
An upload appears to go ok, but the compile fails with:
ERRORTraceback (most recent call last):
  File "./luat", line 298, in <module>
    transport.writeln("node.compile(\"" + args.dest + "\")\r")
  File "./luat", line 106, in writeln
    self.performcheck(data)
  File "./luat", line 73, in performcheck
    sys.stdout.write("\r\n send string    : '%s'" % data)
NameError: global name 'data' is not defined
While I'm aware that node.compile due to out of memory, this appears to be a code error?

**Comment by eyaleb** [comment]
I found this too. I think that the problem is in line I got this too. When a send error happens we enter a block with an error.

Maybe line 71
```
expected = expected.split("\r")[0]
```
should be
```
data = expected.split("\r")[0]
```
