### ISSUE TITLE
No serial/port error message

### ISSUE THREAD

**Issue by nofxx** [4refr0nt/luatool#48]
In a first use, lost some minutes figuring out the current error, thought it was some OS issue.

```
Traceback (most recent call last):
  File "/usr/bin/luatool.py", line 192, in <module>
    transport = decidetransport(args)
  File "/usr/bin/luatool.py", line 168, in decidetransport
    return SerialTransport(cliargs.port, cliargs.baud, cliargs.delay)
  File "/usr/bin/luatool.py", line 97, in __init__
    raise TransportError(e.strerror)
__main__.TransportError
```

Suggestion:

```
NO TTY: Please provide --port. Eg: /dev/ttyUSB*
```

PS.: I nice bet to detect tty is check for platform, linux: `/dev/ttyUSB*` mac: `/dev/tty.usbmodel*`
Thanks for the gem!

**Comment by siddharthsingh** [comment]
Use the command with sudo
