### ISSUE TITLE
No proper answer from MCU on ESP8266 ESP-12E and raspberry Pi 3 B

### ISSUE THREAD

**Issue by Tomek0029** [4refr0nt/luatool#51]
Hello I flashed my ESP8266 ESP-12E with NodeMCU by raspberry Pi 3 B. All was okay.  On ` minicom -b 115200 -o -D /dev/ttyS0` I can normally connect but if I want to upload some files by exec command: `python luatool.py --port /dev/ttyS0 --src init.lua --dest init.lua --verbose --baud 115200` then I get:
```Upload starting
Stage 1. Deleting old file from flash memory
->file.open("init.lua", "w")Traceback (most recent call last):
File "luatool.py", line 272, in <module>
 transport.writeln("file.open(\"" + args.dest + "\", \"w\")\r")
File "luatool.py", line 111, in writeln
self.performcheck(data)
File "luatool.py", line 61, in performcheck
raise Exception('No proper answer from MCU')
Exception: No proper answer from MCU
```
I have connect only RXD and TXD pins, when I'm connecting GPIO0 to GND and run it by baud 9600 its the same, please help me. When I try to the same on ESPlorer then I get double sending a command but not all command. Something like this:
```
print('TEST')
print('TES
```

Guys please help me!

**Comment by Testi89** [comment]
Did you also wire GND?

**Comment by ghost** [comment]
I had the same problem with the luatool. Using minicom everything went right. I've got the exception " No proper answer from MCU". That's way the answer to a command should be something different than an empty line. But my NodeMCU software allways answers with an empty line. Replacing the exception call with a `break` statement in a while loop did the trick.

https://github.com/4refr0nt/luatool/blob/master/luatool/luatool.py#L72

However that's just a quick fix.
